FROM golang:1.9

COPY . /go/src/github.com/leansoftx/play-with-docker

WORKDIR /go/src/github.com/leansoftx/play-with-docker

# install dep and run 'dep ensure' to download dependency
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

RUN dep ensure

RUN rm -rf /go/src/github.com/leansoftx/play-with-docker